[package]
name = "debug-symbol"
version = "0.1.0"
authors = ["Tal Liberman <talliberman@users.noreply.github.com>"]
edition = "2018"
license = "MIT"
publish = false

[dependencies]
frida-gum = { path = "../../../frida-gum", features = ["invocation-listener"] }
lazy_static = "1.4"
