[package]
name = "frida-build"
version = "0.1.0"
authors = ["meme <keegan@sdf.org>"]
edition = "2018"
license = "wxWindows"
repository = "https://github.com/meme/frida-rust"
description = "Build support for Frida Rust bindings"
