[package]
name = "frida-sys"
version = "0.2.3"
authors = ["Keegan Saunders <keegan@undefinedbehaviour.org>"]
edition = "2018"
license = "wxWindows"
repository = "https://github.com/meme/frida-rust"
description = "Rust generated bindings for Frida"

[features]
auto-download = ["frida-build"]

[build-dependencies]
bindgen = "0.57.0"
frida-build = { path = "../frida-build", version = "0.2.0", optional = true }

[badges]
maintenance = { status = "experimental" }
