[package]
name = "frida-sys"
version = "0.4.4"
authors = ["Keegan Saunders <keegan@undefinedbehaviour.org>", "Shmarya Rubenstein <github@shmarya.net>"]
edition = "2018"
license = "wxWindows"
repository = "https://github.com/frida/frida-rust"
description = "Rust generated bindings for Frida"

[features]
auto-download = ["frida-build"]

[build-dependencies]
bindgen = "0.69.1"
frida-build = { path = "../frida-build", version = "0.2.1", optional = true }

[badges]
maintenance = { status = "experimental" }
