[package]
name = "frida-sys"
version = "0.1.1"
authors = ["meme <keegan@sdf.org>"]
edition = "2018"
license = "wxWindows"
repository = "https://github.com/meme/frida-rust"
description = "Rust generated bindings for Frida"

[features]
auto-download = ["frida-build"]

[build-dependencies]
bindgen = "0.57.0"
frida-build = { path = "../frida-build", version = "0.1.0", optional = true }

[badges]
maintenance = { status = "experimental" }
